name: area
on: push
jobs:
  area:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - run: pip install -q yowasp-yosys
      - run: curl -sSL -o hd.lib https://raw.githubusercontent.com/The-OpenROAD-Project/OpenROAD-flow-scripts/master/flow/platforms/sky130hd/lib/sky130_fd_sc_hd__tt_025C_1v80.lib
      - run: yowasp-yosys -V && python3 exp/run.py
